---
title: "Population-level-analysis"
author: "Francesco Neri"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

#libraries
library(tidyverse)
library(readxl)
library(scales)
library(RColorBrewer)

# custom functions
## source load_functions
source("C:/Users/ffran/AppData/Local/R/functions/load_functions.R")

## load functions
function_names <- c("add_fold_change",
                    "update_variable_values",
                    "add_fold_change")

load_functions(function_names)

```

## Load Data

```{r loading data}
# data
df <- read_xlsx(path = "C:/Users/ffran/Dropbox/R/Wirtz-collaboration/2023-0913_Analysis of Buck images-v2_population-level.xlsx")

str_replace_all_underscore <- function(string, pattern) {
  str_replace_all(string, pattern, replacement = "_")
}

colnames(df) <- colnames(df) %>%
  str_replace_all_underscore(pattern = "-") %>%
  str_replace_all_underscore(pattern = " ") %>%
  str_replace_all(pattern = "/", replacement = "VS")

# adjust batch/experiment # and serum values

# create function to update values of a variable in a df
update_variable_values <- function(data, variable, old_values, new_values){
  stopifnot(is.data.frame(data))
  stopifnot(is_character(variable))
  stopifnot(length(old_values) == length(new_values))
  
  df <- data
  
  for (i in seq_along(old_values)) {
    df[ df[ , variable] == old_values[i], variable] <- new_values[i]
  }
  
  df
}

df <- update_variable_values(df, "Batch", 5:7, 1:3) %>%
  update_variable_values(., "Serum", "Serum starved", "Serum Starved")

df

```
## Calculate relative fold change

IR data normalized based on Mock staining

```{r add fold change}

# create vector containing the variables we want to calculate the fold change for
all_var_names <- colnames(df)

var_interval_start <- grep(all_var_names, pattern = "Narea_overall")
var_interval_end <- grep(all_var_names, pattern = "CintAll_c4_overall")

variables_to_add_fc <- all_var_names[var_interval_start:var_interval_end]

# create df with additional fold change columns
df_fc <- add_fold_change(data = df,
                vars_to_normalize = variables_to_add_fc,
                grouping_arguments = c("Batch", "Plate", "Cell_line", "Legend", "Serum", "Channel2", "Channel3"),
                normalization_variable = "Legend",
                normalization_value = "Mock"
                )
df_fc

```
## Fold change plots

### p21 & yH2AX plots

```{r 2D fold change plots}

# filter df_fc clean to have only IR wells stained with Abs
ctl_stains <- c("Isotype CTL Ab", "no 1°Ab", "Isot CTL Ab high")

df_fc_clean <- df_fc %>%
  filter(Legend == "IR") %>%
  filter(!(Channel2 %in% ctl_stains)) %>%
  filter(!(Channel3 %in% ctl_stains))

df_fc_clean$Batch <- df_fc_clean$Batch %>% as.factor() # needed for labeling in ggplot

# separate IMR90 from HMVECL data
df_fc_clean_IMR90 <- df_fc_clean %>%
  filter(Cell_line == "IMR90")

df_fc_clean_IMR90_p21 <- df_fc_clean_IMR90 %>%
  filter(Channel2 == "p21")

df_fc_clean_IMR90_yH2AX <- df_fc_clean_IMR90 %>%
  filter(Channel2 == "yH2AX")

df_fc_clean_HMVECL <- df_fc_clean %>%
  filter(Cell_line == "HMVECL")

df_fc_clean_HMVECL_p21 <- df_fc_clean_HMVECL %>%
  filter(Channel2 == "p21")

df_fc_clean_HMVECL_yH2AX <- df_fc_clean_HMVECL %>%
  filter(Channel2 == "yH2AX")

# set ggplot theme
theme_set(theme_bw())

# set 2nd marker palette
palette <- rev(brewer.pal(9, "Set1"))

# ggplot

plot_2D_fold_change <- function(data,
                                faceting_Ch2 = FALSE,
                                xlab = "Fold Change 1st Marker \n(p21/yH2AX)",
                                ylab = "Fold Change 2nd Marker \n(LaminB1/HMGB1/p21/yH2AX") {
  stopifnot(is.data.frame(data))
  stopifnot(is_logical(faceting_Ch2))
  stopifnot(is_character(c(xlab, ylab)))
  
  title <- data$Cell_line %>%
    unique()
  
  # axis limits
  max_x <- max(data$NintAll_c2_overall_fc)
  max_y <- max(data$NintAll_c3_overall_fc)
  
  limits_x <- c(0, max_x * 1.1)
  limits_y <- c(0, max_y * 1.1)
  
  # plot
  ggplot(data) +
    geom_hline(yintercept = 1,
             linetype = "dashed",
             color = "grey") +
    geom_vline(xintercept = 1,
             linetype = "dashed",
             color = "grey") +
    geom_point(
      aes(NintAll_c2_overall_fc,
          NintAll_c3_overall_fc,
          shape = Batch,
          fill = Channel3),
      size = 3) +
    {if (faceting_Ch2 == TRUE) facet_grid(Serum ~ Channel2)} +
    {if (faceting_Ch2 == FALSE) facet_grid(Serum ~ .)} +
    labs(title = title,
         x = xlab,
         y = ylab) +
    scale_x_continuous(
      limits = limits_x,
      breaks = seq(1, (round(max_x))+2, by = 2)
      ) +
    scale_y_continuous(
      limits = limits_y,
      breaks = seq(1, (round(max_y))+2, by = 2)
      ) +
    scale_shape_manual(values = c(21:25)) +
    scale_fill_manual(values = palette) +
    guides(fill = guide_legend(title = "2nd Marker",
                               override.aes=list(shape=21, # needed to fix a legend bug due to use of scale_shape_manual()
                                                 size=4)))
}

plot_2D_fold_change(df_fc_clean_HMVECL, faceting_Ch2 = TRUE)
plot_2D_fold_change(df_fc_clean_IMR90, faceting_Ch2 = TRUE)

```

### p21 plots

```{r p21 plots, fig.dim=c(4.5,5)}

plot_2D_fold_change(df_fc_clean_HMVECL_p21, xlab = "Fold Change 1st Marker \n(p21)")
plot_2D_fold_change(df_fc_clean_IMR90_p21, xlab = "Fold Change 1st Marker \n(p21)")

```

### yH2AX plots

```{r yH2AX plots, fig.dim=c(4.5,5)}

plot_2D_fold_change(df_fc_clean_HMVECL_yH2AX, xlab = "Fold Change 1st Marker \n(yH2AX)")
plot_2D_fold_change(df_fc_clean_IMR90_yH2AX, xlab = "Fold Change 1st Marker \n(yH2AX)")

```


```{r Notes}

### NOTES ###

```

