---
title: "SABGal-comparison-G1vsG2"
author: "Francesco Neri"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      include = FALSE,
                      fig.align='center',
                      out.width="100%",
                      fig.width=7.5,
                      fig.asp=0.618)

# libraries
library(tidyverse)
library(readxl)
library(RColorBrewer)

library(functions) # custom functions

theme_set(theme_bw())

palette <- RColorBrewer::brewer.pal(9,"Set1") %>% .[3:4]

```

```{r load data}

SABGal_EdU <- list(
  "FN027.01" = read.csv(
    here::here(
      "inst","extdata","FN027.01","Single_Cell_Data_2024-02-07.csv"
    )),
  "FN027.02" = read.csv(
    here::here(
      "inst","extdata","FN027.02","Single_Cell_Data_2024-02-07.csv"
    )),
  "FN027.03" = read.csv(
    here::here(
      "inst","extdata","FN027.03_230126","Single_Cell_Data_2024-02-07.csv"
    ))
)

```

```{r df_SABGal_EdU}

# adjust FN27.01
SABGal_EdU$FN027.01 <- SABGal_EdU$FN027.01 %>%
  mutate(
    Condition = str_replace_all(Condition, "_background", "")
  )

df_SABGal_EdU <- SABGal_EdU %>%
  # add the df name as variable to each df
  imap(
    # .x indicates the list object
    ~ .x %>%
      mutate(
        # .y indicates the object name
        Dataset = .y,
        # adjust Dataset labels
        Dataset = str_replace_all(Dataset,
                                  pattern = c("FN027.03" = "3", "FN027.02" = "2", "FN027.01" = "1"))
      ) %>% 
      # reorder cols
      select(Dataset, everything())
    ) %>%
  # merge Datasets into 1 df (for ease of manipulation)
  bind_rows() %>%
  mutate(
    # turn Dataset, Condition, Serum, and Cell.Type into factors
    Dataset = factor(Dataset),
    plate = factor(plate),
    Condition = factor(Condition),
    Serum = factor(Serum, levels = c("FS", "SS")),
    Cell.Type = factor(Cell.Type, levels = c("HMVEC-L", "IMR-90")),
    well = factor(well)
  ) %>%
  # remove background wells
  ## remove background values
  filter(!str_detect(Condition, pattern = "_background")) %>%
  ## adjust Condition factor levels (drop background levels)
  mutate(Condition = forcats::fct_drop(Condition)) %>%
  # split df into subsets based on Dataset, Cell.Type, Serum
  group_by(Dataset, Cell.Type, Serum) %>%
  nest() %>%
  ungroup()

```

```{r scatterplot SABGal vs DNAcontent}

# scatterplot function 
plot_SABGal_DNAcontent <- function(Dataset, Serum, Cell.Type, data) {
  
  ggplot(data) +
    geom_point(
      aes(x = DAPI,
          y = SABGal,
          color = Condition),
      alpha = 1/10
    ) +
    facet_grid(. ~ Condition) +
    scale_x_log10() +
    scale_y_log10() +
    labs(
      title = str_c("Dataset: ", Dataset, "; Cell Type: ", Cell.Type, "; Serum: ", Serum)
    ) +
    scale_color_manual(values = palette %>% set_names(c("CTL", "IR"))) +
    guides(color = guide_legend(override.aes = list(alpha=1)))
  
}

# generate plots
df_SABGal_EdU_plots <- df_SABGal_EdU %>%
  # add plot col with graphs
  mutate(
    scatterplot = pmap(.l = ., .f = plot_SABGal_DNAcontent)
  )

df_SABGal_EdU_plots %>% pull(scatterplot)

```


```{r }

```

- establish DNA content tresholds
- for each well, calculate the median SABGal value for G1 and G2 subpopulations
- plot